cd ..

SET PRODUCT=Лояльность
SET SUBSYSTEM=Розница22
SET DESCENTPR=2002012
SET DESCENT=2002012
SET PLATFORM=80312
v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT%
SET DESCENTPR=2002012_BASE
v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT%


SET PRODUCT=Лояльность
SET SUBSYSTEM=Розница23
SET DESCENTPR=2003009
SET DESCENT=2003009
SET PLATFORM=80312
v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT%
SET DESCENTPR=2003009_BASE
v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT%


SET PRODUCT=Лояльность
SET SUBSYSTEM=Торговля114
SET DESCENTPR=11004011
SET DESCENT=11004011
SET PLATFORM=80312
v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT%


SET PRODUCT=Лояльность
SET SUBSYSTEM=Торговля115
SET DESCENTPR=11005007
SET DESCENT=11005007
SET PLATFORM=80312

v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT%
SET DESCENTPR=11005007_BASE
v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT%
