SET PRODUCT=Лояльность
SET SUBSYSTEM=Розница22
SET DESCENTPR=2002012
SET DESCENT=2002012
SET PLATFORM=80312

cd ../..
v8unpack.exe -E bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe src\%SUBSYSTEM% --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --descent %DESCENT%
pause