SET PRODUCT=Лояльность
SET SUBSYSTEM=Торговля115
SET DESCENTPR=11005007_BASE
SET DESCENT=11005007
SET PLATFORM=80312

cd ../..
v8unpack.exe -B src\%SUBSYSTEM% bin\%PRODUCT%.%SUBSYSTEM%.%DESCENTPR%.cfe --index cmd\%SUBSYSTEM%\index.%DESCENTPR%.json --version %PLATFORM% --descent %DESCENT% --gui 3
pause